### ISSUE TITLE
Compare each state in the US

### ISSUE THREAD

**Issue by markis** [aatishb/covid#4]
Great work on this project! The site is easy to use and informative. :+1: 

I was wondering if would be possible to create a version where each of the states could be compared in a similar way. The data could be interesting since the health care is similar between each state but each governor's response to this crisis has been different.

**Comment by Kronicker76** [comment]
@markis similar question  https://github.com/aatishb/covid/issues/2#issue-589369478. @aatishb thank you for this data and video.  Excellent thought to plot log-log new vs total cases instead of the explicit timeseries.  Thanks!

**Comment by markis** [comment]
In case I wasn't being clear, here is what I am requesting.  I would like to see this page with the us states each broken out:  https://aatishb.com/covidtrends/

**Comment by markis** [comment]
Either I missed it before or you added it.  Either way thank you!

![image](https://user-images.githubusercontent.com/1095826/78509719-2cc59980-775e-11ea-82ae-588f4ab95c03.png)
